name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Optionally generate compile_commands.json

      - uses: ZedThree/clang-tidy-review@v0.22.1
        id: review
        with:
          exclude: "lib/external/*"
          config_file: ".clang-tidy"

      # Uploads an artefact containing clang_fixes.json
      - uses: ZedThree/clang-tidy-review/upload@v0.22.0
        id: upload-review

      # If there are any comments, fail the check
      # We still want the option to merge without 100% clean code
      #- if: steps.review.outputs.total_comments > 0
      #  run: exit 1
